// TEST SYMPTOM SEARCH FUNCTION.
function testSymptomSearch() {
// SHOULD RETURN THE SYMPTOM THAT MATCHES THE USER.

// THE FUNCTION SHOULD RETURN THE SYMPTOMS WHOSE SUBSTRING MATCHES THE USER'S INPUT.

// THE FUNCTION SHOULD HIDE ALL THE SYMPTOMS IF NOTHING MATCHES THE USER INPUT.

// THE FUNCTION SHOULD SHOW THE "CAN'T FIND YOUR SYMPTOM? BUTTON".
}

// =========================================================================================
function testShowSymptomDescription() {
// TEST SHOW SYMPTOM DESCRIPTION FUNCTION.

// THE FUNCTION SHOULD DISPLAY THE BUTTON AT THE BOTTOM OF THE SYMPTOM'S DESCRIPTION.

// THE FUNCTION SHOULD DISPLAY THE BUTTON AT THE BOTTOM OF THE SYMPTOMS DESCRIPTION.

// THE FUNCTION SHOULD HIDE THE SEARCH BAR.

// ==========================================================================================

// FUNCTION TO TEST THE SYSTEM'S TEST FUNCTIONS.
}